name: Build RPM

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Build RPM package
        run: |
          echo Nachinaju telepat!
          make

      - name: Archive Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: RPM
          path: |
            noarch/*
          retention-days: 14


#      - name: Upload artifact
#        uses: actions/upload-artifact@v1.0.0
#        with:
#          name: Binary RPM
#          path: ${{ steps.rpm.outputs.rpm_dir_path }}
