#
#   Builds the RPM and keeps the ZIP
#

name: Build RPM

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'LICENSE'
      - 'README.md'
      - '.gitignore'
      - 'assets/**'
      - 'TODO'
  
  pull_request:
    branches: [ main ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Build RPM package
        run: |
          v="`git describe --tags --abbrev=0`"
          echo "Last tag in Git:$v"
          make BUILD_VERSION=$v

      - name: Archive Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: RPM
          path: |
            video-gadgets-*.noarch.rpm
            video-gadgets-*.tgz
          retention-days: 14

